[package]
name = "advent-of-code-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
substring = "1.4.5"
libmath = "0.2.1"
